title = "mysterium"
baseURL = "https://seraphinush-gaming.com"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-mysterium"
defaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
pluralizelisttitles = false

[params]
description = "blog by seraphinush"
dateFormat = "Monday, January 2, 2006"
trackingId = "UA-66500356-2"
adsenseId = "ca-pub-3598595244893452"
faviconUrl = "https://github.com/seraphinush-gaming/mysterium/blob/master/content/favicon.png?raw=true"
donateUrl = "https://www.paypal.me/seraphinush"
customJs = true

[Languages]
[Languages.en]
  weight = 0
  [[Languages.en.params.nav]]
    title = "about"
    url = "/about"
  [[Languages.en.params.nav]]
    title = "youtube"
    url = "https://www.youtube.com/c/seraphinush-gaming?sub_confirmation=1"
  [[Languages.en.params.nav]]
    title = "twitch"
    url = "https://www.twitch.tv/seraphinush"
  [[Languages.en.params.nav]]
    title = "patreon"
    url = "https://www.patreon.com/seraphinush"
  [[Languages.en.params.nav]]
    title = "feedback"
    url = "https://github.com/seraphinush-gaming/mysterium/issues"

[Languages.ko]
  weight = 1
  [[Languages.ko.params.nav]]
    title = "소개"
    url = "/about"
  [[Languages.ko.params.nav]]
    title = "유튜브"
    url = "https://www.youtube.com/c/seraphinush-gaming?sub_confirmation=1"
  [[Languages.ko.params.nav]]
    title = "트위치"
    url = "https://www.twitch.tv/seraphinush"
  [[Languages.ko.params.nav]]
    title = "페이트리온"
    url = "https://www.patreon.com/seraphinush"
  [[Languages.ko.params.nav]]
    title = "피드백"
    url = "https://github.com/seraphinush-gaming/mysterium/issues"
